baseURL = "https://merch.projektemacher.org/"
languageCode = "de"
title = "Projektemacher"
theme = ["hugo-coder", "projektemacher-base"]
publishDir = "docs"
canonifyurls = true
disableKinds = ["term", "taxonomy"]
languagecode = "de"
defaultcontentlanguage = "de"
